language: bash

dist: trusty
sudo: false

addons:
 apt:
  sources:
   - trusty-media
   - debian-sid
   - ubuntu-toolchain-r-test
  packages:
   - ffmpeg
   - shellcheck
   - libstdc++6

before_install:
 - ./.travis-libjpeg-setup.sh

before_script:
 - wget https://github.com/Steveice10/bannertool/releases/download/1.1.0/bannertool.zip -O /tmp/bannertool.zip
 - unzip -j /tmp/bannertool.zip "linux-x86_64/bannertool"
 - wget https://github.com/dnasdw/3dstool/releases/download/v1.0.22/3dstool_linux_x86_64.tar.gz -O /tmp/3dstool.tar.gz
 - tar -zxvf /tmp/3dstool.tar.gz 3dstool
 - wget https://github.com/profi200/Project_CTR/releases/download/0.15/makerom_015_ctrtool.zip -O /tmp/makerom.zip
 - unzip -j /tmp/makerom.zip "Linux_x86_64/makerom"
 - chmod +x makerom bannertool 3dstool
 - export PATH=$PATH:$PWD

script:
 - bash -c 'shellcheck build_full.sh'
 - bash -c 'shellcheck linuxstuffs/vid2jpgvsauce/build.sh'
 - bash -c 'cd linuxstuffs/vid2jpgvsauce; ./build.sh'
 - bash -c './test.sh'
